### ISSUE TITLE
Error: The server is being accessed through a load balancer, but this driver does not have load balancing enabled

### ISSUE THREAD

**Issue by code4muktesh** [Studio3T/robomongo#1889]
When trying to serverless Atlas database then getting error on windows 10 environment

**Comment by jelgersma** [comment]
Same here, havent found a solution yet. Currently using MongoDB Compass. Due to this problem im considering not to extend the license because this is critical to our operation as we moved to serverless atlas.

**Comment by RishangS** [comment]
Same here, Please post if any solution found

**Comment by aramirez92** [comment]
Same problem with pro version.

**Comment by aramirez92** [comment]
> Same here, Please post if any solution found

[https://github.com/Studio3T/robomongo/issues/1889#issuecomment-1236034850](Solution)

**Comment by RishangS** [comment]
I am using Ubuntu

**Comment by z3ugma** [comment]
I think this is resolved with the new version of Studio 3T 

https://files.studio3t.com/changelog/changelog.txt

```

New: Shell and Tool Updates - Updated the default for the bundled tools to use the most recent versions, 5.0.10 and 100.5.4.
```

**Comment by dested** [comment]
> Same problem, i've solved buying a pro license.

Nothing in the pro plan says anything about load balancer support.

**Comment by jankammerath** [comment]
Still doesn't work in 2022.8.1.

```
MongoDB shell version v5.0.10
================
Warning: the "mongo" shell has been superseded by "mongosh",
which delivers improved usability and compatibility.The "mongo" shell has been deprecated and will be removed in
an upcoming release.
For installation instructions, see
https://docs.mongodb.com/mongodb-shell/install/
================
Error: The server is being accessed through a load balancer, but this driver does not have load balancing enabled :
@(shell):1:6
```

IntelliShell just crashes the mongo shell.

**Comment by roz0n** [comment]
Still not fixed.

**Comment by kaishin** [comment]
I have this issue only when exporting. IntelliShell seems to work fine. I am running the latest version 2022.9.2.
