### ISSUE TITLE
When editing a document that has been requested using a projection, the resulting document is clobbered

### ISSUE THREAD

**Issue by fresheneesz** [Studio3T/robomongo#881]
If I search for documents using a projection that only selects for 1 property, then I click on a field in the table and choose "Edit Document", a window will pop up with the document as fetched from the database (with only the field selected in the projection). If I then modify the value of that field, the whole document is clobbered except for the field that appeared in the "Edit Document" window. 

This is not expected nor desired. If I edit just one value of one field in that "Edit Document" window - I expect that's the only value that will be changed. What robomongo should do here is some kind of diff to figure out what changed, and make only that change.

**Comment by anorsich** [comment]
@schetnikovich Sounds like a crytical issue. We need to fetch full document when editing.

**Comment by revolter** [comment]
Yep, it's a highly critical issue that I noticed the hard way! Is there any possibility for this to be fixed in the next release? Also, is there a way I can help with this?

**Comment by simsekgokhan** [comment]
Hi @revolter , I also agree that this is a very important problem. Currently, we are focused on delivering some critical features Replica Sets and Export/Import. Any help/contribution is very welcome.

**Comment by revolter** [comment]
Could you point me out to a file/function as I'm obviously not accustomed with the code base?

**Comment by simsekgokhan** [comment]
Sure, it should be in robomongo/src/robomongo/core/domain/Notifier.cpp and DocumentTextEditor class is created with "Edit Document". But obviously this is just the start of interface, the problem should probably be fixed in deeper calls which needs the real investigation/work.

Please also see how to build guide and our coding guidelines here:
https://github.com/paralect/robomongo/wiki

Please let me if you need any help.

**Comment by prathamsaroha** [comment]
I also found this the hard way. This is a critical issue.

**Comment by fresheneesz** [comment]
2.5 years and this is still an issue? Come on guys, this is embarrassingly, and should be easy to fix. Just keep track of the properties in the projection and only update those. Why are contributors dragging their feet on this?

**Comment by revolter** [comment]
I think that the best temporary solution is to disable the save button, this way, the most important thing - not lose important data - is prevented, until the save works in the correct way.

Not being able to edit a filtered result is not uncommon, many SQL clients don't allow this at all because of the complexity (e.g. using joins) of the update handling, so I don't believe it would come as a very big surprise, opposed to the surprise of losing potentially production data.

**Comment by acawood777** [comment]
Also found this the hard way...    was still running 1.1
Can confirm that 1.2 only allows View - no Edit option.

**Comment by simsekgokhan** [comment]
@All, we are very sorry for the long delay. The critical part of the issue is addressed in version 1.2. See more: https://blog.robomongo.org/robo-3t-1-2/#a3
